### ISSUE TITLE
searching not work?

### ISSUE THREAD

**Issue by yuomtheara** [bower/search#69]
searching not work?
I try type `select2, bootbox, jquery ...`, but don't show any thing.

**Comment by anderskristo** [comment]
Same for me, get this error: 

```
TypeError: keyword.toLowerCase is not a function
    at http://bower.io/search/dist/app.js:12:8886
    at Array.some (native)
    at http://bower.io/search/dist/app.js:12:8844
    at Array.every (native)
    at matchesByKeyword (http://bower.io/search/dist/app.js:12:8798)
    at http://bower.io/search/dist/app.js:12:9459
    at Function.filter (http://bower.io/search/dist/app.js:11:1821)
    at find (http://bower.io/search/dist/app.js:12:9178)
    at Scope.$scope.search (http://bower.io/search/dist/app.js:12:10830)
    at http://bower.io/search/dist/app.js:8:12316
```

**Comment by desandro** [comment]
The problem was caused by a package, [calsa](https://github.com/hosseinpanahi/calsa/blob/83bdf481a/bower.json), which had an array inside its `keywords` array. Adding type checking resolved this.
